# Generated by Django 4.2.7 on 2023-11-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='defaults/cover.avif', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='defaults/profile.png', upload_to='profile_images/'),
        ),
    ]
