# Generated by Django 4.2.7 on 2023-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bio_alter_user_cover_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='defaults/cover2.jfif', upload_to='cover_images/'),
        ),
    ]
